### ISSUE TITLE
[BUG] Odoo v15/14; when using "view" cmd => TypeError: parent._trigger_up is not a function

### ISSUE THREAD

**Issue by mads-vkd** [Tardo/OdooTerminal#125] opened 2023-09-18 09:26 UTC
**Basic Info. (please complete the following information):**
 - Odoo version: 14.0, 15.0
 - Browser: Chrome
 - Command: view

**Describe the bug**
When attempting to view a record via the view command, above mentioned error occurs. Tested on various instances across versions 14 and 15; unable to replicate on v16 and v13 instances.
Following the errors first appearence it will pop up again when navigating the UI; most often when changing views.

When attempting to view a specific dataset ("view sale.order 1546"), a brief error is shown in the terminal itself.
To get the full error traceback and console log, attempt to view the model ("view sale.order")

**Expected behavior**
To be taken to the view of the model/record designated using the view command.

**Screenshots**
![image](https://github.com/Tardo/OdooTerminal/assets/67997947/d293b057-27db-4e1b-a910-6b9b90a82d27)

**Additional context**
Traceback:
TypeError: parent._trigger_up is not a function
    at Class._trigger_up (https:///web/content/210-4583773/web.assets_common.js:4805:462)
    at Class.trigger_up (https:///web/content/210-4583773/web.assets_common.js:4805:280)
    at https:///web/content/210-4583773/web.assets_common.js:4869:342
    at new Promise (<anonymous>)
    at Class.loadViews (https:///web/content/210-4583773/web.assets_common.js:4869:307)
    at Class.open (https:///web/content/211-5f6701f/web.assets_backend.js:2240:186)
    at prototype.<computed> [as open] (https:///web/content/210-4583773/web.assets_common.js:4653:488)
    at e.id.d.type (chrome-extension://fdidojpjkbpfplcdmeaaehnjfkgpbhad/dist/pub/loader.mjs:1:16957)
    at as.callback (chrome-extension://fdidojpjkbpfplcdmeaaehnjfkgpbhad/dist/pub/loader.mjs:1:17158)
    at #fe (chrome-extension://fdidojpjkbpfplcdmeaaehnjfkgpbhad/dist/pub/loader.mjs:1:89531)

**Comment by Tardo** [comment] 2023-09-20 01:01
Thanks for the report!

I can't reproduce the issue on 15.0... 14.0 should be fixed in next version 10.3.1.

**Closed** 2023-09-23 22:31 UTC
Labels: bug
